const blocklist = [
  "*://*.doubleclick.net/*",
  "*://*.googlesyndication.com/*",
  "*://*.googleadservices.com/*",
  "*://*.googletagmanager.com/*",
  "*://*.googletagservices.com/*",
  "*://*.adsense.com/*",
  "*://*.adservice.google.com/*",
  "*://*.g.doubleclick.net/*",
  "*://*.googlevideo.com/*adformat=*",
  "*://*.googlevideo.com/*&adformat=*",
  "*://*.googlevideo.com/*ad_break=*",
  "*://*.googlevideo.com/*&ad_break=*",
  "*://*.googlevideo.com/*ctier=*",
  "*://*.googlevideo.com/*oad=*",
  "*://*.googlevideo.com/*&oad=*",
  "*://*.youtube.com/api/stats/ads*",
  "*://*.youtube.com/pagead/*",
  "*://*.youtube.com/ptracking*",
  "*://*.youtube.com/youtubei/v1/player*adformat*",
  "*://*.youtube.com/youtubei/v1/player*ad_break*",
  "*://*.youtube.com/youtubei/v1/player*oad*",
  "*://*.youtube.com/get_midroll_info*",
  "*://*.adform.net/*",
  "*://*.zedo.com/*",
  "*://*.taboola.com/*",
  "*://*.outbrain.com/*",
  "*://*.advertising.com/*",
  "*://*.criteo.com/*",
  "*://*.amazon-adsystem.com/*",
  "*://*.moatads.com/*",
  "*://*.pubmatic.com/*",
  "*://*.rubiconproject.com/*",
  "*://*.smartadserver.com/*",
  "*://*.serving-sys.com/*",
  "*://*.adsrvr.org/*",
  "*://*.popads.net/*",
  "*://*.propellerads.com/*",
  "*://*.onclickads.net/*"
];

if (typeof self !== "undefined") {
  self.blocklist = blocklist;
}
  